//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_User
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> IsCanlogin { get; set; }
        public Nullable<int> ShowOrder1 { get; set; }
        public Nullable<int> ShowOrder2 { get; set; }
        public string PinYin1 { get; set; }
        public string PinYin2 { get; set; }
        public string Face_Img { get; set; }
        public string Levels { get; set; }
        public string Dptid { get; set; }
        public string CreatePer { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string LastLoginIP { get; set; }
    }
}
